import Head from "next/head";
import NavBar from "@/components/NavBar";
import About from "@/components/About";
import Projects from "@/components/Projects";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ''}>
      <Head>
        <title>Adrian Greksa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative max-w-screen-lg mx-auto px-10 z-10 w-full bg-slate-100 shadow-2xl dark:bg-gray-900 dark:text-white">
        <NavBar darkMode={darkMode}  setDarkMode={setDarkMode}/>
        <About />
        <Projects />
        
        {/* Skills */}
        <section>
          <div>
            <h2 className="text-4xl flex justify-center my-5">Languages</h2>
          </div>
        </section>

        {/* Current Interests */}
        <section>
          <h2 className="text-5xl text-center my-5">Now?</h2>
          <div className="flex flex-col justify-center gap-2 text-center">
            <p>
              Currently studying algorithms, working with Next.js and
              TailwindCss.
            </p>
            <p>Reading 'Fabric of the Cosmos' Brian Greene.</p>
            <p>
              Reach out to me if you would like to chat.
            </p>
          </div>
        </section>

      </main>
    </div>
  );
}
